name: lap_fitness
description: A clone of main LAP Fitness application developed by Isaac Urman and Darrian Yang
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  collection: ^1.18.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lap.png
    - assets/images/lap2.png
    - assets/images/post.png
    - assets/images/profile_me.png
    - assets/images/profile.png
    - assets/images/lunges.png
    - assets/images/push-ups.png
    - assets/images/squats.png
    - assets/images/water_bottle.png

flutter_launcher_icons:
  image_path: 'assets/images/lap2.png'
  android: true
  ios: true
