// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKVvcV9EPJL_OXx3I1p6z4forM-kAiqEg',
    appId: '1:1076168022651:web:c48ba297634030ba68a0de',
    messagingSenderId: '1076168022651',
    projectId: 'lap-fitness',
    authDomain: 'lap-fitness.firebaseapp.com',
    databaseURL: 'https://lap-fitness-default-rtdb.firebaseio.com',
    storageBucket: 'lap-fitness.appspot.com',
    measurementId: 'G-476VRMEZBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbWZSXYnGGnSYEfXoLAMjZmUnUs8XAFcM',
    appId: '1:1076168022651:android:bc0964a941f7118a68a0de',
    messagingSenderId: '1076168022651',
    projectId: 'lap-fitness',
    databaseURL: 'https://lap-fitness-default-rtdb.firebaseio.com',
    storageBucket: 'lap-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf744vF-01zLswYrP-68K6IX4aaYOhIIQ',
    appId: '1:1076168022651:ios:b914677aa00fa0a068a0de',
    messagingSenderId: '1076168022651',
    projectId: 'lap-fitness',
    databaseURL: 'https://lap-fitness-default-rtdb.firebaseio.com',
    storageBucket: 'lap-fitness.appspot.com',
    iosClientId:
        '1076168022651-9rnt6g0pg5jsaglkbnl0565ejq1ru4l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapFitnessClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf744vF-01zLswYrP-68K6IX4aaYOhIIQ',
    appId: '1:1076168022651:ios:b914677aa00fa0a068a0de',
    messagingSenderId: '1076168022651',
    projectId: 'lap-fitness',
    databaseURL: 'https://lap-fitness-default-rtdb.firebaseio.com',
    storageBucket: 'lap-fitness.appspot.com',
    iosClientId:
        '1076168022651-9rnt6g0pg5jsaglkbnl0565ejq1ru4l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapFitnessClone',
  );
}
