// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrquklDanvegDSTBXd3LUemKHQu3OwcZc',
    appId: '1:171214035542:web:f838044ed2c652551279f7',
    messagingSenderId: '171214035542',
    projectId: 'lap-firebase-ac2a7',
    authDomain: 'lap-firebase-ac2a7.firebaseapp.com',
    storageBucket: 'lap-firebase-ac2a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVY61CRzsO8K-LLTxg7qUPc0f2Q3xYP6k',
    appId: '1:171214035542:android:498c9f3f565fa4471279f7',
    messagingSenderId: '171214035542',
    projectId: 'lap-firebase-ac2a7',
    storageBucket: 'lap-firebase-ac2a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKq4QpnjjcOTCeLsFgazBN59zCUTPZFU',
    appId: '1:171214035542:ios:81bf3a82e29ca6e81279f7',
    messagingSenderId: '171214035542',
    projectId: 'lap-firebase-ac2a7',
    storageBucket: 'lap-firebase-ac2a7.appspot.com',
    iosClientId: '171214035542-cdlrjv5ebqna2s8hjbnkm6fbifqqndip.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADKq4QpnjjcOTCeLsFgazBN59zCUTPZFU',
    appId: '1:171214035542:ios:81bf3a82e29ca6e81279f7',
    messagingSenderId: '171214035542',
    projectId: 'lap-firebase-ac2a7',
    storageBucket: 'lap-firebase-ac2a7.appspot.com',
    iosClientId: '171214035542-cdlrjv5ebqna2s8hjbnkm6fbifqqndip.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
